### ISSUE TITLE
'AdminErrorList' object has no attribute 'data'

### ISSUE THREAD

**Issue by koralarts** [datahub/grappelli-nested-inlines#9]
I'm getting an error `'AdminErrorList' object has no attribute 'data'` whenever I go to the `Add` portion of the admin panel.

My code looks as follows:

```
class ChoiceInline(NestedTabularInline):
     # attributes

class QuestionInline(NestedStackedInline):
     inlines = [ChoiceInline]
     # attributes

class ExamAdmin(NestedModelAdmin):
     inlines = [QuestionInline]
     # attributes
```

Settings:

```
INSTALLED_APPS = (
    'grappelli_nested',
    'grappelli',
    'django.contrib.admin',
    ...
)
```

I am using the following versions of the modules:

```
Python == 3.4.2
Django == 1.7.4
django-grappelli == 2.6.3
grappelli-nested-inlines == 0.5.7
```

I haven't seen any issue about this bug/error. It could be a dependency issue.

**Comment by cwyalpha** [comment]
it's a known bug of nested-inlines.
i've tried this solution and it works for me.
https://github.com/silverfix/django-nested-inlines/commit/aeb7a1f84cd41acb8efa66483908f79a2fcd511a

**Comment by allanjamesvestal** [comment]
I've implemented the Silverfix patch for this. It should be completely working in Django 1.7, and I'll be tracking the development of Grappelli for Django 1.8. I hope to have a 1.8-compatible release soon after Grapelli's.

Once I've made sure I've applied any necessary JavaScript and template changes as well, I'll be pushing a new version to GitHub and PyPI. Thanks for your patience and your feedback.
